name: "Build and Pack"

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0 # tag=v3.0.2
      with:
        dotnet-version: 6.0.x

    - name: Restore Windows
      run: dotnet restore --runtime=win10-x64

    - name: Build Windows
      run: dotnet build IdlImpTool --no-restore --runtime=win10-x64

    - name: Restore Linux
      run: dotnet restore --runtime=linux-x64

    - name: Build Linux
      run: dotnet build IdlImpTool --no-restore --runtime=linux-x64

    - name: Pack IdlImporter (also builds any runtime)
      run: dotnet pack IDLImporter --include-symbols --no-restore -o .

    - name: Pack IdlImpTool Everything (also builds any runtime)
      run: dotnet pack IdlImpTool --include-symbols --no-restore -o .

    - name: Publish Artifacts
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
      with:
        name: NugetPackages
        path: |
          ./*.nupkg
          ./*.snupkg

  publish-nuget:
    name: "Publish NuGet package"
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # renovate: tag=v3.0.0
      with:
        path: artifacts

    - name: Publish to Nuget
      run: dotnet nuget push artifacts/**/*.*nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
