name: "Build and Pack"

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: 6.0.x

    - name: Restore Windows
      run: dotnet restore --runtime=win10-x64

    - name: Build Windows
      run: dotnet build IdlImpTool --no-restore --runtime=win10-x64

    - name: Restore Linux
      run: dotnet restore --runtime=linux-x64

    - name: Build Linux
      run: dotnet build IdlImpTool --no-restore --runtime=linux-x64

    - name: Pack IdlImporter (also builds any runtime)
      run: dotnet pack IDLImporter --include-symbols --no-restore -o .

    - name: Pack IdlImpTool Everything (also builds any runtime)
      run: dotnet pack IdlImpTool --include-symbols --no-restore -o .

    - name: Publish Artifacts
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: NugetPackages
        path: |
          ./*.nupkg
          ./*.snupkg

  publish-nuget:
    name: "Publish NuGet package"
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        path: artifacts

    - name: Publish to Nuget
      run: dotnet nuget push artifacts/**/*.*nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
