name: "Build and Pack"

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # v2.1.0
      with:
        dotnet-version: 6.0.x

    - name: Restore Windows
      run: dotnet restore --runtime=win10-x64

    - name: Build Windows
      run: dotnet build IdlImpTool --no-restore --runtime=win10-x64

    - name: Restore Linux
      run: dotnet restore --runtime=linux-x64

    - name: Build Linux
      run: dotnet build IdlImpTool --no-restore --runtime=linux-x64

    - name: Pack IdlImporter (also builds any runtime)
      run: dotnet pack IDLImporter --include-symbols --no-restore -o .

    - name: Pack IdlImpTool Everything (also builds any runtime)
      run: dotnet pack IdlImpTool --include-symbols --no-restore -o .

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NugetPackages
        path: |
          ./*.nupkg
          ./*.snupkg

  publish-nuget:
    name: "Publish NuGet package"
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@076f0f7dd036d87e8e04f5f00d614e790308961b # v3.0.0
      with:
        path: artifacts

    - name: Publish to Nuget
      run: dotnet nuget push artifacts/**/*.*nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
